### ISSUE TITLE
[Customweb_RealexCw] «(Customweb_Mvc_Controller_Dispatcher) No controller provided in the request»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [tradefurniturecompany/site#169]
```
[2020-03-29 01:21:15] realexcw.ERROR: (Customweb_Mvc_Controller_Dispatcher) No controller provided in the request.
No controller provided in the request.
#0 lib/internal/Customweb/Mvc/Controller/Dispatcher.php(63): Customweb_Mvc_Controller_AbstractAdapter->extractControllerName(Object(Customweb_Core_Http_ContextRequest))
#1 app/code/Customweb/RealexCw/Controller/Endpoint/Index.php(95): Customweb_Mvc_Controller_Dispatcher->dispatch(Object(Customweb_Core_Http_ContextRequest))
#2 vendor/magento/framework/Interception/Interceptor.php(58): Customweb\RealexCw\Controller\Endpoint\Index->execute()
#3 vendor/magento/framework/Interception/Interceptor.php(138): Customweb\RealexCw\Controller\Endpoint\Index\Interceptor->___callParent('execute', Array)
#4 vendor/magento/framework/Interception/Interceptor.php(153): Customweb\RealexCw\Controller\Endpoint\Index\Interceptor->Magento\Framework\Interception\{closure}()
#5 generated/code/Customweb/RealexCw/Controller/Endpoint/Index/Interceptor.php(26): Customweb\RealexCw\Controller\Endpoint\Index\Interceptor->___callPlugins('execute', Array, Array)
#6 vendor/magento/framework/App/Action/Action.php(108): Customweb\RealexCw\Controller\Endpoint\Index\Interceptor->execute()
#7 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 vendor/magento/framework/Interception/Interceptor.php(138): Customweb\RealexCw\Controller\Endpoint\Index\Interceptor->___callParent('dispatch', Array)
#9 vendor/magento/framework/Interception/Interceptor.php(153): Customweb\RealexCw\Controller\Endpoint\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 generated/code/Customweb/RealexCw/Controller/Endpoint/Index/Interceptor.php(39): Customweb\RealexCw\Controller\Endpoint\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#11 vendor/magento/framework/App/FrontController.php(159): Customweb\RealexCw\Controller\Endpoint\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#12 vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Customweb\RealexCw\Controller\Endpoint\Index\Interceptor))
#13 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#14 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#15 vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#21 vendor/magento/framework/App/Http.php(137): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#23 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#24 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#25 generated/code/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#26 vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http\Interceptor->launch()
#27 pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#28 {main}
object(Customweb_Core_Http_ContextRequest)#940 (0) {
}
```

**Comment by dmitry-fedyuk** [comment]
I have implemented a logging in `lib/internal/Customweb/Mvc/Controller/AbstractAdapter.php`.
