### ISSUE TITLE
[Global Payments / Realex] The «Place order» button is not working sometimes: «Cannot read properties of undefined (reading 'forEach') at Object.isValidStreet»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [tradefurniturecompany/site#239]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.isValidStreet (validation.js:107:24)
    at Object.isValidAddress (validation.js:64:27)
    at Object.validate (validation.js:42:34)
    at additional-validators.js:48:26
    at Array.forEach (<anonymous>)
    at Object.validate (additional-validators.js:47:24)
    at UiClass.placeOrder (placeOrder.js:98:42)
    at HTMLButtonElement.<anonymous> (knockout.js:4255:62)
    at HTMLButtonElement.dispatch (jquery.js:5226:27)
    at elemData.handle (jquery.js:4878:29)
```

![01](https://user-images.githubusercontent.com/83204/203889069-bc7bc2a2-5174-4f82-a2d2-18e77bce3187.png)

**Comment by dmitry-fedyuk** [comment]
The failure point: `vendor/realexpayments/hpp/view/frontend/web/js/model/validation.js:107`
```javascript
street.forEach(function (item) {
```

**Comment by dmitry-fedyuk** [comment]
`quote.shippingAddress().street` is not updated when the customer enters a new street.

**Comment by dmitry-fedyuk** [comment]
How to reproduce:
1) Checkout as a guest
2) Do not fill the «Street Address» field
3) Correctly fill all other fields and click the «Place Order» button.
4) The system warns that the «Street Address» field should be filled.
5) Fill the «Street Address» field.
6) The «Place Order» button became broken (because the system did not correctly handle the changed value of the «Street Address» field).
